AWSTemplateFormatVersion: '2010-09-09' 
Resources:
  IAMRoleCP:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: AWSCodePipelinePatchingRole
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Service: 'cloudformation.amazonaws.com'
            Action: 'sts:AssumeRole'
  IAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties: 
      PolicyName: AWSCodePipelinePatchingPolicy
      Roles: 
        - !Ref IAMRoleCP
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Sid: 'SSM'
            Effect: 'Allow'
            Action: 
              - 'ssm:CreateAssociation'
              - 'ssm:DescribeDocument'
              - 'ssm:GetDocument'
              - 'ssm:CreateDocument'
              - 'ssm:ListAssociations'
              - 'ssm:DeleteDocument'
              - 'ssm:DeleteAssociation'
            Resource: '*'
          - Sid: 'IAM'
            Effect: 'Allow'
            Action: 
              - 'iam:DeleteRole'
              - 'iam:GetRole'
              - 'iam:GetRolePolicy'
              - 'iam:ListAttachedRolePolicies'
              - 'iam:ListRolePolicies'
              - 'iam:CreateRole'
              - 'iam:PutRolePolicy'
              - 'iam:DeleteRolePolicy'
              - 'iam:PassRole'
            Resource: '*'
          # - Sid: 'EC2'
          #   Effect: 'Allow'
          #   Action: 
          #     - 'ec2:DescribeInstances'
          #     - 'ec2:DescribeInstanceAttribute'
          #     - 'ec2:DescribeNetworkInterfaces'
          #     - 'ec2:DescribeInstanceCreditSpecifications'
          #     - 'ec2:RunInstances'
          #     - 'ec2:CreateTags'
          #     - 'ec2:TerminateInstances'
          #   Resource: '*'
          - Sid: 'SNS'
            Effect: 'Allow'
            Action: 
              - 'sns:*'
            Resource: '*'
          - Sid: 'CloudFormation'
            Effect: 'Allow'
            Action: 
              - 'cloudformation:CreateStack'
              - 'cloudformation:DeleteStack'
              - 'cloudformation:DescribeStacks'
            Resource: '*'