version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade awscli cfn-lint

  pre_build:
    commands:
      - echo Checking CloudFormation templates...
      - cfn-lint templates/*.yml

  build:
    commands:
      - echo Finding the latest artifact in S3 $PIPELINE_BUCKET
      - |
        LATEST_ARTIFACT=$(aws s3api list-objects-v2 --bucket $PIPELINE_BUCKET --query "Contents | sort_by(@, &LastModified)[-1].Key" --output text)
        echo "Latest artifact: $LATEST_ARTIFACT"
        
      - echo Downloading the latest artifact from S3...
      - aws s3 cp s3://$PIPELINE_BUCKET/$LATEST_ARTIFACT .
      
      - echo Listing contents of the current directory after download...
      - ls -l

      - echo Extracting artifact...
      - unzip $LATEST_ARTIFACT -d extracted-artifacts || echo "Unzip failed"

      - echo Moving DeleteSnapshot.zip to root directory...
      - mv extracted-artifacts/zip/DeleteSnapshot.zip .

      - echo Listing contents of the current directory after moving...
      - ls -l

      - echo Copying DeleteSnapshot.zip to the target S3 bucket...
      - aws s3 cp DeleteSnapshot.zip s3://$PIPELINE_BUCKET/DeleteSnapshot.zip

  post_build:
    commands:
      - echo Cleaning up temporary files...
      - rm -rf extracted-artifacts $LATEST_ARTIFACT DeleteSnapshot.zip

artifacts:
  files:
    - '**/*'
