AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: Patching
      RoleArn: arn:aws:iam::007695491693:role/service-role/AWSCodePipelineServiceRole-us-east-1-Patching
      ArtifactStore:
        Type: S3
        Location: !Sub 'codepipeline-${AWS::AccountId}-${AWS::Region}'
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ConnectionArn: arn:aws:codestar-connections:us-east-1:007695491693:connection/b965019a-d6b5-4bfa-ab0b-2596e6996504
                FullRepositoryId: dereban25/codepipeline
                BranchName: patching
                DetectChanges: false
              RunOrder: 1

      #   - Name: Deploy
      #     Actions:
      #       - Name: DeployAction
      #         ActionTypeId:
      #           Category: Deploy
      #           Owner: AWS
      #           Provider: CloudFormation
      #           Version: '1'
      #         InputArtifacts:
      #           - Name: SourceArtifact
      #         Configuration:
      #           ActionMode: CREATE_UPDATE
      #           StackName: Patching
      #           Capabilities: CAPABILITY_NAMED_IAM
      #           TemplatePath: SourceArtifact::MainCloudFormation.yml
      #           RoleArn: arn:aws:iam::007695491693:role/cdk-hnb659fds-cfn-exec-role-007695491693-us-east-1
      #           ParameterOverrides: !Sub |
      #             {
      #               "ArtifactName": "SourceArtifact",
      #               "FileName": "Parameters.json"
      #             }
      #         RunOrder: 1
      # ExecutionMode: QUEUED

  PipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'codepipeline-${AWS::AccountId}-${AWS::Region}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  CodePipelineName:
    Description: "The name of the CodePipeline"
    Value: !Ref CodePipeline
