AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicName:
    Description: Name for the SNS topic
    Type: String

  SNSDisplayName:
    Description: Display name for the SNS topic
    Type: String

  SNSEmail:
    Description: Email address for SNS subscription
    Type: String

  MyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: SourceArtifact::SNSForPatchingCloudFormation.yml