AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicName:
    Description: Name for the SNS topic
    Type: String

  SNSDisplayName:
    Description: Display name for the SNS topic
    Type: String

  SNSEmail:
    Description: Email address for SNS subscription
    Type: String

Resources:
  MyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/codepipeline-007695491693-us-east-1/Patching/SourceArti/xsqAnrE/SNSForPatchingCloudFormation.yml

Outputs:
  MyStack:
    Description: "The output from the nested stack"
    Value: MyStack