AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSTopicName:
    Description: Name for the SNS topic
    Type: String
  SNSDisplayName:
    Description: Display name for the SNS topic
    Type: String
  SNSEmail:
    Description: Email address for SNS subscription
    Type: String

Resources: 
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SNSTopicName
      DisplayName: !Ref SNSDisplayName
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SNSEmail
      Protocol: email
      TopicArn: !Ref SNSTopic

Outputs:
  Art:
    Description: "The constructed Template URL for debugging"
    Value: 
      Fn::Sub:
        - "https://s3.amazonaws.com/${BucketName}/${ObjectKey}"
        - BucketName: !GetArtifactAtt [SourceArtifact, BucketName]
          ObjectKey: !GetArtifactAtt [SourceArtifact, ObjectKey]
          
# Resources:
#   MyStack:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       TemplateURL: 
#       Fn::Sub:
#           - "https://s3.amazonaws.com/${BucketName}/${ObjectKey}"
#           - BucketName: !GetArtifactAtt [SourceArtifact, BucketName]
#             ObjectKey: !GetArtifactAtt [SourceArtifact, ObjectKey]
#       Parameters:
#         SNSTopicName: !Ref SNSTopicName
#         SNSDisplayName: !Ref SNSDisplayName
#         SNSEmail: !Ref SNSEmail