AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template for LambdaDeleteSnapshotRole"
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Lambda-DeleteSnapshot
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      
  IAMPolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
        PolicyName: Lambda-SSM-Policy
        Roles:
          - !Ref IAMRole
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "KMS"
                Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                  - "kms:RetireGrant"
                Resource: "*"
              - Sid: "CloudWatchLogs"
                Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                Resource: "*"
              - Sid: "STS"
                Effect: "Allow"
                Action:
                  - "sts:AssumeRole"
                Resource:
                  - "arn:aws:iam::*:role/AWS-SystemsManager-AutomationExecutionRole"
              - Sid: "Organization"
                Effect: "Allow"
                Action:
                  - "organizations:ListAccounts"
                  - "organizations:DescribeOrganization"
                Resource: "*"
              - Sid: "SNS"
                Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource: "arn:aws:sns:us-east-1:{account_id_root}:Max"