AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  AutomationAdministrationRole:
    Type: String
    Description: Name for the IAM role for SSM Patching Automation
    Default: Custom-SystemsManager-AutomationAdministrationRole

  AutomationExecutionRole:
    Type: String
    Description: Name for the IAM role for SSM Patching Automation
    Default: Custom-SystemsManager-AutomationExecutionRole

  TargetAccountList:
    Type: CommaDelimitedList
    Description: List of AWS target account IDs

Resources:
  AWSSystemsManagerAutomationAdministrationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref AutomationAdministrationRole
      Description: Role with permissions to manage and execute AWS Systems Manager Automation tasks.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                !ForEach AccountId in !Ref TargetAccountList
                  - !Sub 'arn:aws:iam::${AccountId}:role/${AutomationExecutionRole}'
            Action: 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service: 'ssm.amazonaws.com'
            Action: 'sts:AssumeRole'

  CustomSystemsManagerAutomationAdministrationRoleInlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: Custom-SystemsManager-AutomationExecutionRoleInlinePolicy
      Roles:
        - !Ref AWSSystemsManagerAutomationAdministrationRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: "STS"
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource: !Sub 'arn:aws:iam::*:role/${AutomationExecutionRole}'