AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.

Parameters:

  S3Bucket:
    Type: String
    Description: The S3 bucket where the Lambda function ZIP file is stored

  S3Key:
    Type: String
    Default: DeleteSnapshot.zip
    Description: The S3 key for the Lambda function ZIP file
    
  Days:
    Type: String
    Description: Number of days for the function to process
    Default: '2'

  ExceptionAccountIds:
    Type: String
    Description: Exception account IDs
    Default: '905418384534'

  ExceptMasterAccount:
    Type: String
    Description: Exclude master account (True or False)
    Default: 'False'

  RegionsToProcess:
    Type: String
    Description: Regions to process (comma-separated)
    Default: 'us-east-1'

  RoleName:
    Type: String
    Description: Role name for automation execution
    Default: AWS-SystemsManager-AutomationExecutionRole

  SnsTopicArn:
    Type: String
    Description: SNS Topic ARN for notifications
    Default: arn:aws:sns:us-east-1:007695491693:Max

  TagKey:
    Type: String
    Description: Tag key for filtering
    Default: Patching

  TagValue:
    Type: String
    Description: Tag value for filtering
    Default: DeleteAllow

  LambdaRoleName:
    Type: String
    Default: arn:aws:iam::007695491693:role/Lambda-DeleteSnapshot
    Description: Existing IAM role name for Lambda function

  LambdaFunctionName:
    Type: String
    Default: LambdaDeleteSnapshot
    Description: Lambda Name

Resources:
  DeleteSnapshot:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
      Description: ''
      MemorySize: 128
      Timeout: 30
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          DAYS: !Ref Days
          EXCEPTION_ACCOUNT_IDS: !Ref ExceptionAccountIds
          EXCEPT_MASTER_ACCOUNT: !Ref ExceptMasterAccount
          REGIONS_TO_PROCESS: !Ref RegionsToProcess
          ROLE_NAME: !Ref RoleName
          SNS_TOPIC_ARN: !Ref SnsTopicArn
          TAG_KEY: !Ref TagKey
          TAG_VALUE: !Ref TagValue
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      SnapStart:
        ApplyOn: None
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 ? * * *)
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Role: !Ref LambdaRoleName