AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your Lambda function for snapshot deletion.

Parameters:

  S3Bucket:
    Type: String
    Description: The S3 bucket where the Lambda function ZIP file is stored

  S3Key:
    Type: String
    Description: The S3 key for the Lambda function ZIP file
    
  Days:
    Type: String
    Description: Number of days for the function to process

  ExceptionAccountIds:
    Type: String
    Description: Exception account IDs

  ExceptMasterAccount:
    Type: String
    Description: Exclude master account (True or False)

  RegionsToProcess:
    Type: String
    Description: Regions to process (comma-separated)

  RoleName:
    Type: String
    Description: Role name for automation execution

  SnsTopicArn:
    Type: String
    Description: SNS Topic ARN for notifications

  TagKey:
    Type: String
    Description: Tag key for filtering

  TagValue:
    Type: String
    Description: Tag value for filtering

  LambdaRoleName:
    Type: String
    Default: LambdaDeleteSnapshotRole
    Description: Lambda Role name

  LambdaFunctionName:
    Type: String
    Default: LambdaDeleteSnapshot
    Description: Lambda function name

Resources:
  LambdaDeleteSnapshotRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: sts:AssumeRole
  LambdaDeleteSnapshotRoleInlinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaDeleteSnapshotRoleInlinePolicy
      Roles:
        - Ref: LambdaDeleteSnapshotRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:RetireGrant
            Resource: 
              - '*'
          - Effect: Allow
            Action:
              - logs:CreateLogStream
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: !Sub 'arn:aws:iam::*:role/${RoleName}'
          - Effect: Allow
            Action:
              - organizations:ListAccounts
              - organizations:DescribeOrganization
            Resource: 
              - '*'
          - Effect: Allow
            Action:
              - sns:Publish
            Resource: !Ref SnsTopicArn
  DeleteSnapshot:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
      Description: Lambda function for deleting snapshots
      MemorySize: 128
      Timeout: 30
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          DAYS: !Ref Days
          EXCEPTION_ACCOUNT_IDS: !Ref ExceptionAccountIds
          EXCEPT_MASTER_ACCOUNT: !Ref ExceptMasterAccount
          REGIONS_TO_PROCESS: !Ref RegionsToProcess
          ROLE_NAME: !Ref RoleName
          SNS_TOPIC_ARN: !Ref SnsTopicArn
          TAG_KEY: !Ref TagKey
          TAG_VALUE: !Ref TagValue
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 ? * * *)
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Role: !GetAtt LambdaDeleteSnapshotRole.Arn
