Resources:
  MyPatchBaseline:
    Type: 'AWS::SSM::PatchBaseline'
    Properties:
      Name: !Ref BaselineName
      OperatingSystem: WINDOWS
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              PatchFilters:
                - Key: PRODUCT
                  Values:
                    - WindowsServer2016
            ApproveAfterDays: 7
            ComplianceLevel: CRITICAL

Parameters:
  BaselineName:
    Type: String
    Description: The name of the Patch Baseline